apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-injector-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-injector-controller
subjects:
- kind: ServiceAccount
  name: secret-injector-controller
  namespace: secret-injector-system