apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretinjectors.config.example.com
spec:
  group: config.example.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              remoteServerURL:
                type: string
              targetDeployment:
                type: string
              secretKeys:
                type: array
                items:
                  type: string
              headers:
                type: object
                additionalProperties:
                  type: string
              refreshInterval:
                type: string
            required:
            - remoteServerURL
            - targetDeployment
            - secretKeys
          status:
            type: object
            properties:
              lastSync:
                type: string
                format: date-time
              secretHash:
                type: string
              ready:
                type: boolean
              message:
                type: string
  scope: Namespaced
  names:
    plural: secretinjectors
    singular: secretinjector
    kind: SecretInjector